create table if not exists public.profile_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('player', 'coach', 'scout')),
  sport text null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists profile_roles_user_role_sport_unique_idx
  on public.profile_roles (
    user_id,
    role,
    coalesce(lower(sport), '')
  );

create unique index if not exists profile_roles_one_primary_per_user_idx
  on public.profile_roles (user_id)
  where is_primary = true;

alter table public.profile_roles enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_roles'
      and policyname = 'Authenticated users can view profile roles'
  ) then
    create policy "Authenticated users can view profile roles"
      on public.profile_roles
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_roles'
      and policyname = 'Users can insert own profile roles'
  ) then
    create policy "Users can insert own profile roles"
      on public.profile_roles
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_roles'
      and policyname = 'Users can update own profile roles'
  ) then
    create policy "Users can update own profile roles"
      on public.profile_roles
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_roles'
      and policyname = 'Users can delete own profile roles'
  ) then
    create policy "Users can delete own profile roles"
      on public.profile_roles
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;

insert into public.profile_roles (user_id, role, sport, is_primary)
select
  p.id,
  case
    when lower(coalesce(p.role, '')) in ('athlete', 'player', 'sports player', 'sport player') then 'player'
    when lower(coalesce(p.role, '')) in ('coach', 'trainer', 'manager', 'assistant coach') then 'coach'
    when lower(coalesce(p.role, '')) in ('scout', 'talent scout', 'recruiter') then 'scout'
    else 'player'
  end,
  nullif(trim(coalesce(p.main_sport, '')), ''),
  true
from public.profiles p
where not exists (
  select 1
  from public.profile_roles pr
  where pr.user_id = p.id
);
